# Generated by Django 4.2.7 on 2024-01-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='owner',
            new_name='user',
        ),
    ]
